spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: ${RABBIT_URL}
    port: 5672
    virtual-host: /
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}

  cloud:
    config:
      enabled: false

  application:
    name: connector-data-service

keycloak:
  auth-server-url: ${AUTHENTICATION_BASE_URL}
  realm: ${AUTHENTICATION_REALM}
  resource: ${AUTHENTICATION_CLIENT_ID}
  public-client: false
  bearer-only: true

server:
  address: 0.0.0.0
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}
    registerWithEureka: true
    fetchRegistry: true

management:
  port: 8081
  endpoints:
    web:
      exposure:
        include: '*'