spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  rabbitmq:
    host: ${RABBIT_URL}
    port: 5672
    virtual-host: /
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}

  cloud:
    config:
      enabled: false

    # ------------------
    # routing properties
    # ------------------
    gateway:
      discovery:
        locator:
          enabled: true
      filter:
        secure-headers:
          disable: Authorization
      routes:
        - uri: lb://CONNECTOR-MANAGEMENT-SERVICE/
          predicates:
            - Path=/services/management/**
          filters:
            - RewritePath=/services/management/(?<segment>.*),/api/v1/$\{segment}

        - uri: lb://CONNECTOR-DATA-SERVICE/
          predicates:
            - Path=/services/data/**
          filters:
            - RewritePath=/services/data/(?<segment>.*),/api/v1/$\{segment}

        - uri: lb://DATA-STORE/
          predicates:
            - Path=/services/store/**
          filters:
            - RewritePath=/services/store/(?<segment>.*),/api/v1/$\{segment}

  application:
    name: routing-proxy

server:
  address: 0.0.0.0
  port: ${APP_PORT}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}
    registerWithEureka: true
    fetchRegistry: true

management:
  port: 8181
  endpoints:
    web:
      exposure:
        include: '*'