spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: ${RABBIT_URL}
    port: 5672
    virtual-host: /
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}

  cloud:
    config:
      enabled: false

  jpa:
    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

  application:
    name: meta-store

  datasource:
    url: jdbc:postgresql://${DB_URI}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

#security:
#  # CHANGEME
#  configurations:
#    - path: /somepath
#      role: somerole

server:
  address: 0.0.0.0
  port: ${APP_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY}
    registerWithEureka: true
    fetchRegistry: true

management:
  port: 8181
  endpoints:
    web:
      exposure:
        include: '*'