spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: ${RABBIT_URL}
    port: 5672
    virtual-host: /
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}

  cloud:
    config:
      enabled: false

  application:
    name: data-store

security:
  # CHANGEME
  configurations:
    - path: /somepath
      role: somerole

#influxDB:
#  url: ${INFLUXDATA_URL}
 # org: ${INFLUXDATA_ORG}
 # bucket: ${INFLUXDATA_BUCKET}
 # token: ${INFLUXDATA_TOKEN}

keycloak:
  auth-server-url: ${AUTH_URL}
  realm: ${AUTH_REALM}
  resource: ${AUTH_RESOURCE}
  public-client: true

server:
  address: 0.0.0.0
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}
    registerWithEureka: false
    fetchRegistry: false

management:
  port: 8081
  endpoints:
    web:
      exposure:
        include: '*'